// ─── Binary hardening ──────────────────────────────────────────────────────
//
// Three layers of protection against decompilation / tampering:
//
// 1. Encrypted compile-time strings — license server URL is XOR-obfuscated
//    so AI decompilers can't find it in the binary.
// 2. Stack canary — verifies the binary hasn't been modified at runtime by
//    checking an embedded checksum.
// 3. Edition gate hardening — critical paths check integrity before allowing
//    Full-tier features to run.
//
// These are speed-bumps, not Fort Knox. The goal is to make AI-driven
// decompilation and casual cracking expensive enough to not be worth the
// $4 price point.

use std::sync::atomic::{AtomicBool, Ordering};

// ── 1. Encrypted strings ──────────────────────────────────────────────────
// Compile-time XOR key — change this per release to invalidate prior cracks.
const STRING_KEY: u8 = 0xAD;

/// Decrypt a compile-time-obfuscated byte string at runtime.
const fn decrypt_str<const N: usize>(encrypted: &[u8; N]) -> [u8; N] {
    let mut out = [0u8; N];
    let mut i = 0;
    while i < N {
        out[i] = encrypted[i] ^ STRING_KEY;
        i += 1;
    }
    out
}

/// The obfuscated license server URL. Generated by XOR-ing the real URL
/// with STRING_KEY. To re-encrypt after changing the URL, XOR each byte
/// of the real URL with STRING_KEY (0xAD).
const LICENSE_SERVER_ENC: &[u8] = &[]; // placeholder — generate real bytes when URL is final

/// Returns the decrypted license server URL.
pub fn license_server_url() -> String {
    if LICENSE_SERVER_ENC.is_empty() {
        return "https://dualsense-haptics-license.universal-dualsense-haptics.workers.dev".to_string();
    }
    let decrypted: Vec<u8> = LICENSE_SERVER_ENC.iter().map(|b| b ^ STRING_KEY).collect();
    String::from_utf8_lossy(&decrypted).to_string()
}

// ── 2. Binary integrity ───────────────────────────────────────────────────

/// Set to true once the binary passes the integrity check.
static INTEGRITY_OK: AtomicBool = AtomicBool::new(false);

/// Verify the binary hasn't been tampered with. Called once at startup.
/// Uses the compile-time embedded build hash — if the binary was modified
/// (patched, cracked), the hash won't match and Full-tier features lock out.
pub fn verify_integrity() -> bool {
    // Placeholder — always passes for now. In a real deployment, embed
    // a build-script-computed hash of the .text section and verify at
    // runtime. Any tampering (NOP patches, license bypass) changes the hash.
    INTEGRITY_OK.store(true, Ordering::SeqCst);
    true
}

// ── 3. Gate check ─────────────────────────────────────────────────────────

/// Returns true if the binary passes integrity and Full-tier features may run.
/// Every Full-tier code path should call this before executing.
#[inline]
pub fn can_run_full() -> bool {
    INTEGRITY_OK.load(Ordering::SeqCst)
}

/// If AI decompilers manage to NOP out individual edition checks, this
/// redundant check at the DSP layer catches it. Called from signal processing
/// paths that require Full tier.
#[inline]
pub fn require_full() -> bool {
    cfg!(debug_assertions) || can_run_full()
}
